
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Shri
 */
public class Admin_Panel extends javax.swing.JFrame {

    Mysql_Con c = new Mysql_Con();
    
    public Admin_Panel() {
        initComponents();
        load_quote();
        load_money_data();
    }
    
    void load_quote(){
        try {
            String qry = "SELECT * FROM quote ORDER BY RAND() LIMIT 1;", q = "";
            ResultSet sent = c.get_data(qry);
            if(sent.next()){
                q = sent.getString(1);
                quote.setText(q);
            }
            else{
                c.message("Unable to Load Quote.");
            }
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(Admin_Panel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    void load_money_data(){
        double sum_all = 0,sum_admin =0;
        String all_qry = "SELECT SUM(Money) FROM users";
        String admin_qry = "SELECT SUM(Money) FROM users WHERE User_Name = 'admin'";
        try {
            ResultSet all_sum_amt = c.get_data(all_qry);
            ResultSet admin_sum_amt = c.get_data(admin_qry);
            if(all_sum_amt.next() && admin_sum_amt.next()){
                sum_all = all_sum_amt.getDouble(1);
                sum_admin = admin_sum_amt.getDouble(1);
            }
            else{
                c.message("Unable to Fetch More Data");
            }
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(Admin_Panel.class.getName()).log(Level.SEVERE, null, ex);
        }
        double users_amt = sum_all - sum_admin;
        money_data_label.setText("Total Users Amount Available :- "+ users_amt +" || Admin Amount :- "+sum_admin);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        main = new javax.swing.JPanel();
        Head = new javax.swing.JPanel();
        head_img_label = new javax.swing.JLabel();
        h1 = new javax.swing.JLabel();
        h11 = new javax.swing.JLabel();
        quote_pane = new javax.swing.JScrollPane();
        quote = new javax.swing.JTextArea();
        Transactions_btn = new javax.swing.JButton();
        Add_Train_Panel_btn = new javax.swing.JButton();
        Show_Train_Panel_btn = new javax.swing.JButton();
        money_data_label = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(500, 316));
        setUndecorated(true);

        main.setBackground(new java.awt.Color(255, 255, 255));
        main.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 204, 255), 5));
        main.setForeground(new java.awt.Color(255, 255, 255));
        main.setMinimumSize(new java.awt.Dimension(500, 316));

        Head.setBackground(new java.awt.Color(255, 255, 255));
        Head.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 153, 255), 5));
        Head.setMinimumSize(new java.awt.Dimension(0, 467));

        head_img_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photos/Control Panel/Admin_Portal.jpg"))); // NOI18N
        head_img_label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                head_img_labelMouseClicked(evt);
            }
        });

        h1.setFont(new java.awt.Font("Segoe UI Symbol", 1, 36)); // NOI18N
        h1.setForeground(new java.awt.Color(51, 204, 255));
        h1.setText("Admin");

        h11.setFont(new java.awt.Font("Segoe UI Symbol", 1, 36)); // NOI18N
        h11.setForeground(new java.awt.Color(51, 204, 255));
        h11.setText("Portal");

        quote.setColumns(20);
        quote.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        quote.setLineWrap(true);
        quote.setRows(5);
        quote.setWrapStyleWord(true);
        quote.setBorder(javax.swing.BorderFactory.createTitledBorder("Quote of the Day"));
        quote.setFocusable(false);
        quote_pane.setViewportView(quote);

        javax.swing.GroupLayout HeadLayout = new javax.swing.GroupLayout(Head);
        Head.setLayout(HeadLayout);
        HeadLayout.setHorizontalGroup(
            HeadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeadLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(head_img_label)
                .addGap(18, 18, 18)
                .addGroup(HeadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(h1)
                    .addComponent(h11))
                .addGap(18, 18, 18)
                .addComponent(quote_pane)
                .addContainerGap())
        );
        HeadLayout.setVerticalGroup(
            HeadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeadLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(HeadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(HeadLayout.createSequentialGroup()
                        .addComponent(h1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(h11))
                    .addComponent(head_img_label)
                    .addComponent(quote_pane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Transactions_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photos/Control Panel/transaction.jpg"))); // NOI18N
        Transactions_btn.setToolTipText("Transactions");
        Transactions_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Transactions_btnActionPerformed(evt);
            }
        });

        Add_Train_Panel_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photos/Control Panel/train.png"))); // NOI18N
        Add_Train_Panel_btn.setToolTipText("Train Panel");
        Add_Train_Panel_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Add_Train_Panel_btnActionPerformed(evt);
            }
        });

        Show_Train_Panel_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photos/Control Panel/Available_Trains.png"))); // NOI18N
        Show_Train_Panel_btn.setToolTipText("Trains Available");
        Show_Train_Panel_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Show_Train_Panel_btnActionPerformed(evt);
            }
        });

        money_data_label.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        money_data_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        money_data_label.setText("More Info");
        money_data_label.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 255), 2));

        javax.swing.GroupLayout mainLayout = new javax.swing.GroupLayout(main);
        main.setLayout(mainLayout);
        mainLayout.setHorizontalGroup(
            mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Head, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(mainLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(money_data_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(mainLayout.createSequentialGroup()
                        .addComponent(Transactions_btn)
                        .addGap(30, 30, 30)
                        .addComponent(Add_Train_Panel_btn)
                        .addGap(30, 30, 30)
                        .addComponent(Show_Train_Panel_btn)))
                .addContainerGap())
        );
        mainLayout.setVerticalGroup(
            mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainLayout.createSequentialGroup()
                .addComponent(Head, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Transactions_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Add_Train_Panel_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Show_Train_Panel_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(money_data_label, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(main, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(main, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void head_img_labelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_head_img_labelMouseClicked
        this.setVisible(false);
        new Sign_Up().setVisible(true);
    }//GEN-LAST:event_head_img_labelMouseClicked

    private void Transactions_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Transactions_btnActionPerformed
        this.setVisible(false);
        new User_Transactions("admin").setVisible(true);
    }//GEN-LAST:event_Transactions_btnActionPerformed

    private void Add_Train_Panel_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Add_Train_Panel_btnActionPerformed
        new Train_Panel().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_Add_Train_Panel_btnActionPerformed

    private void Show_Train_Panel_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Show_Train_Panel_btnActionPerformed
        this.setVisible(false);
        new Show_Train().setVisible(true);
    }//GEN-LAST:event_Show_Train_Panel_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin_Panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin_Panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin_Panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin_Panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin_Panel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Add_Train_Panel_btn;
    private javax.swing.JPanel Head;
    private javax.swing.JButton Show_Train_Panel_btn;
    private javax.swing.JButton Transactions_btn;
    private javax.swing.JLabel h1;
    private javax.swing.JLabel h11;
    private javax.swing.JLabel head_img_label;
    private javax.swing.JPanel main;
    private javax.swing.JLabel money_data_label;
    private javax.swing.JTextArea quote;
    private javax.swing.JScrollPane quote_pane;
    // End of variables declaration//GEN-END:variables
}
