import java.awt.Color;
import java.sql.*;
import java.util.logging.*;

public class Home extends javax.swing.JFrame {

    Mysql_Con c = new Mysql_Con(); 
    String uname;
    public Home(String user_name) throws ClassNotFoundException, SQLException {
        initComponents();
        uname = user_name;
        user.setText(uname);
        set_amt();
    }

    private Home() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    void set_amt() throws ClassNotFoundException, SQLException{
        String qry = "SELECT * FROM users WHERE User_Name = '"+uname+"'";
        double amt = 0;
        ResultSet rs = c.get_data(qry);
        if(rs.next()){
            amt = rs.getDouble("Money");
        }
        amt_value.setText(""+amt);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        body = new javax.swing.JPanel();
        header = new javax.swing.JPanel();
        user = new javax.swing.JLabel();
        AMOUNT = new javax.swing.JLabel();
        amt_value = new javax.swing.JLabel();
        add_amt = new javax.swing.JButton();
        User_Settings = new javax.swing.JButton();
        Transactions = new javax.swing.JButton();
        Book_Train_Ticket = new javax.swing.JButton();
        My_Bookingsss = new javax.swing.JButton();
        transfer_money_btn = new javax.swing.JButton();
        log_out_btn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        body.setBackground(new java.awt.Color(255, 255, 255));
        body.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 204), 10));

        header.setBackground(new java.awt.Color(0, 0, 0));

        user.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        user.setForeground(new java.awt.Color(255, 255, 255));
        user.setText("User Name");

        AMOUNT.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        AMOUNT.setForeground(new java.awt.Color(255, 255, 255));
        AMOUNT.setText("Wallet Amount :- ");

        amt_value.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        amt_value.setForeground(new java.awt.Color(255, 255, 255));
        amt_value.setText("0");

        add_amt.setBackground(new java.awt.Color(0, 0, 0));
        add_amt.setFont(new java.awt.Font("Arial Black", 1, 11)); // NOI18N
        add_amt.setForeground(new java.awt.Color(255, 255, 255));
        add_amt.setText("+");
        add_amt.setOpaque(false);
        add_amt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                add_amtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                add_amtMouseExited(evt);
            }
        });
        add_amt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_amtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(user)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(AMOUNT)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(amt_value)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(add_amt, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(amt_value, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(AMOUNT, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(add_amt)
                    .addComponent(user, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE))
                .addContainerGap())
        );

        User_Settings.setBackground(new java.awt.Color(255, 255, 255));
        User_Settings.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photos/user.jpg"))); // NOI18N
        User_Settings.setToolTipText("Profile Settings");
        User_Settings.setOpaque(false);
        User_Settings.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                User_SettingsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                User_SettingsMouseExited(evt);
            }
        });
        User_Settings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                User_SettingsActionPerformed(evt);
            }
        });

        Transactions.setBackground(new java.awt.Color(255, 255, 255));
        Transactions.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photos/transaction.jpg"))); // NOI18N
        Transactions.setToolTipText("Transactions");
        Transactions.setOpaque(false);
        Transactions.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                TransactionsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                TransactionsMouseExited(evt);
            }
        });
        Transactions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TransactionsActionPerformed(evt);
            }
        });

        Book_Train_Ticket.setBackground(new java.awt.Color(255, 255, 255));
        Book_Train_Ticket.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photos/book_trian_ticket.jpg"))); // NOI18N
        Book_Train_Ticket.setToolTipText("Book_Train_Ticket");
        Book_Train_Ticket.setOpaque(false);
        Book_Train_Ticket.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Book_Train_TicketMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Book_Train_TicketMouseExited(evt);
            }
        });
        Book_Train_Ticket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Book_Train_TicketActionPerformed(evt);
            }
        });

        My_Bookingsss.setBackground(new java.awt.Color(255, 255, 255));
        My_Bookingsss.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photos/my_bookings.jpg"))); // NOI18N
        My_Bookingsss.setToolTipText("My Bookings");
        My_Bookingsss.setOpaque(false);
        My_Bookingsss.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                My_BookingsssMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                My_BookingsssMouseExited(evt);
            }
        });
        My_Bookingsss.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                My_BookingsssActionPerformed(evt);
            }
        });

        transfer_money_btn.setBackground(new java.awt.Color(255, 255, 255));
        transfer_money_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photos/transfer_money.jpg"))); // NOI18N
        transfer_money_btn.setToolTipText("Transfer Money");
        transfer_money_btn.setOpaque(false);
        transfer_money_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                transfer_money_btnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                transfer_money_btnMouseExited(evt);
            }
        });
        transfer_money_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transfer_money_btnActionPerformed(evt);
            }
        });

        log_out_btn.setBackground(new java.awt.Color(255, 255, 255));
        log_out_btn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        log_out_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photos/logout.jpg"))); // NOI18N
        log_out_btn.setToolTipText("Logout");
        log_out_btn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        log_out_btn.setFocusPainted(false);
        log_out_btn.setOpaque(false);
        log_out_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                log_out_btnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                log_out_btnMouseExited(evt);
            }
        });
        log_out_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                log_out_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout bodyLayout = new javax.swing.GroupLayout(body);
        body.setLayout(bodyLayout);
        bodyLayout.setHorizontalGroup(
            bodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(header, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(bodyLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(bodyLayout.createSequentialGroup()
                        .addComponent(User_Settings)
                        .addGap(18, 18, 18)
                        .addComponent(Transactions))
                    .addGroup(bodyLayout.createSequentialGroup()
                        .addComponent(My_Bookingsss)
                        .addGap(18, 18, 18)
                        .addComponent(transfer_money_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(bodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Book_Train_Ticket, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(log_out_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        bodyLayout.setVerticalGroup(
            bodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bodyLayout.createSequentialGroup()
                .addComponent(header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(bodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(User_Settings, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Transactions, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Book_Train_Ticket, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(bodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bodyLayout.createSequentialGroup()
                        .addGroup(bodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(My_Bookingsss, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)
                            .addComponent(transfer_money_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(log_out_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(body, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(body, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void add_amtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_amtActionPerformed
        this.setVisible(false);
        try {
            new Add_Money(uname).setVisible(true);
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_add_amtActionPerformed

    private void log_out_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_log_out_btnActionPerformed
        this.setVisible(false);
        uname = "";
        new Sign_Up().setVisible(true);
    }//GEN-LAST:event_log_out_btnActionPerformed

    private void User_SettingsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_User_SettingsMouseEntered
        User_Settings.setBackground(Color.red);
    }//GEN-LAST:event_User_SettingsMouseEntered

    private void User_SettingsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_User_SettingsMouseExited
        User_Settings.setBackground(Color.white);
    }//GEN-LAST:event_User_SettingsMouseExited

    private void User_SettingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_User_SettingsActionPerformed
        this.setVisible(false);
        new Profile(uname).setVisible(true);
    }//GEN-LAST:event_User_SettingsActionPerformed

    private void add_amtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_add_amtMouseEntered
        add_amt.setBackground(Color.GREEN);
        add_amt.setForeground(Color.black);
    }//GEN-LAST:event_add_amtMouseEntered

    private void add_amtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_add_amtMouseExited
        add_amt.setForeground(Color.white);
        add_amt.setBackground(Color.GRAY);
    }//GEN-LAST:event_add_amtMouseExited

    private void TransactionsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TransactionsMouseEntered
        Transactions.setBackground(Color.red);
    }//GEN-LAST:event_TransactionsMouseEntered

    private void TransactionsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TransactionsMouseExited
        Transactions.setBackground(Color.white);
    }//GEN-LAST:event_TransactionsMouseExited

    private void TransactionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TransactionsActionPerformed
        this.setVisible(false);
        new User_Transactions(uname).setVisible(true);
    }//GEN-LAST:event_TransactionsActionPerformed

    private void Book_Train_TicketMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Book_Train_TicketMouseEntered
        Book_Train_Ticket.setBackground(Color.red);
    }//GEN-LAST:event_Book_Train_TicketMouseEntered

    private void Book_Train_TicketMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Book_Train_TicketMouseExited
        Book_Train_Ticket.setBackground(Color.WHITE);
    }//GEN-LAST:event_Book_Train_TicketMouseExited

    private void Book_Train_TicketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Book_Train_TicketActionPerformed
        this.setVisible(false);
        new Book_Ticket(uname).setVisible(true);
    }//GEN-LAST:event_Book_Train_TicketActionPerformed

    private void My_BookingsssMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_My_BookingsssMouseEntered
        My_Bookingsss.setBackground(Color.red);
    }//GEN-LAST:event_My_BookingsssMouseEntered

    private void My_BookingsssMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_My_BookingsssMouseExited
        My_Bookingsss.setBackground(Color.white);
    }//GEN-LAST:event_My_BookingsssMouseExited

    private void My_BookingsssActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_My_BookingsssActionPerformed
        this.setVisible(false);
        new My_Bookings(uname).setVisible(true);
    }//GEN-LAST:event_My_BookingsssActionPerformed

    private void log_out_btnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_log_out_btnMouseEntered
        log_out_btn.setBackground(Color.red);
    }//GEN-LAST:event_log_out_btnMouseEntered

    private void log_out_btnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_log_out_btnMouseExited
        log_out_btn.setBackground(Color.white);
    }//GEN-LAST:event_log_out_btnMouseExited

    private void transfer_money_btnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_transfer_money_btnMouseEntered
        transfer_money_btn.setBackground(Color.red);
    }//GEN-LAST:event_transfer_money_btnMouseEntered

    private void transfer_money_btnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_transfer_money_btnMouseExited
        transfer_money_btn.setBackground(Color.white);
    }//GEN-LAST:event_transfer_money_btnMouseExited

    private void transfer_money_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transfer_money_btnActionPerformed
        this.setVisible(false);
        new Transfer_Money(uname).setVisible(true);
    }//GEN-LAST:event_transfer_money_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AMOUNT;
    private javax.swing.JButton Book_Train_Ticket;
    private javax.swing.JButton My_Bookingsss;
    private javax.swing.JButton Transactions;
    private javax.swing.JButton User_Settings;
    private javax.swing.JButton add_amt;
    private javax.swing.JLabel amt_value;
    private javax.swing.JPanel body;
    private javax.swing.JPanel header;
    private javax.swing.JButton log_out_btn;
    private javax.swing.JButton transfer_money_btn;
    private javax.swing.JLabel user;
    // End of variables declaration//GEN-END:variables
}
