
import java.awt.print.PrinterException;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


public class My_Bookings extends javax.swing.JFrame {

    String user;
    Mysql_Con c = new Mysql_Con();
    public My_Bookings(String uname) {
        initComponents();
        user = uname;
        load_bookings();
    }

    private My_Bookings() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    
    void load_bookings(){
        DefaultTableModel model = (DefaultTableModel) booking_table.getModel();
        model.setRowCount(0);
        String qry = "SELECT ID,T_Date,Source,Destination,Ticket_Class,Tickets_Total_Amount from tickets WHERE User_Name = '"+user+"'";
        try {
            ResultSet bookings = c.get_data(qry);
            while(bookings.next()){
                int id = bookings.getInt("ID");
                String t_date = bookings.getDate("T_DATE").toString();
                String t_source = bookings.getString("Source");
                String t_dest = bookings.getString("Destination");
                String tk_class = bookings.getString("Ticket_Class");
                double trip_amt = bookings.getDouble("Tickets_Total_Amount");
                Object[] row = {id,t_date,t_source,t_dest,tk_class,trip_amt};
                model.addRow(row);
            }
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(My_Bookings.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ticket_window = new javax.swing.JFrame();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        ticket_area = new javax.swing.JTextArea();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        main_panel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        booking_table = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        id_tf = new javax.swing.JTextField();

        ticket_window.setMinimumSize(new java.awt.Dimension(600, 550));
        ticket_window.setPreferredSize(new java.awt.Dimension(550, 508));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 255, 255), 10));

        ticket_area.setColumns(20);
        ticket_area.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        ticket_area.setRows(5);
        jScrollPane2.setViewportView(ticket_area);

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setText("Print");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton4.setText("<< Back");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 510, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton3)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addContainerGap())
        );

        javax.swing.GroupLayout ticket_windowLayout = new javax.swing.GroupLayout(ticket_window.getContentPane());
        ticket_window.getContentPane().setLayout(ticket_windowLayout);
        ticket_windowLayout.setHorizontalGroup(
            ticket_windowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        ticket_windowLayout.setVerticalGroup(
            ticket_windowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        main_panel.setBackground(new java.awt.Color(255, 255, 255));
        main_panel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255), 10));

        booking_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Booking ID", "Travel Date", "From", "To", "Class", "Amount Paid"
            }
        ));
        jScrollPane1.setViewportView(booking_table);

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("=====> My Bookings <=====");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jButton1.setText("Cancel Tickets");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jButton2.setText("Show Ticket");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        id_tf.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        id_tf.setText("Booking_ID");

        javax.swing.GroupLayout main_panelLayout = new javax.swing.GroupLayout(main_panel);
        main_panel.setLayout(main_panelLayout);
        main_panelLayout.setHorizontalGroup(
            main_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(main_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(main_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 640, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, main_panelLayout.createSequentialGroup()
                        .addComponent(id_tf)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        main_panelLayout.setVerticalGroup(
            main_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(main_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(main_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(main_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton1)
                        .addComponent(jButton2))
                    .addComponent(id_tf))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(main_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(main_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        double amt = 0;
        int id = Integer.parseInt(id_tf.getText());
        if(Integer.toString(id).length() == 0 || Integer.toString(id).equals("Booking_ID")){
            c.message("Please Fill the Correct Value in Field");
        }
        else{
            String get_qry = "SELECT Tickets_Total_Amount FROM tickets WHERE ID = "+id;
            String del_qry = "DELETE FROM tickets WHERE ID ="+id;
            int response = JOptionPane.showConfirmDialog(null, "Do you Really want to Cancel Your Ticket ?");
            if(response == 0){
                try {
                    ResultSet get_res = c.get_data(get_qry);
                    while(get_res.next()){
                        amt = get_res.getDouble("Tickets_Total_Amount");
                    }
                    String add_qry = "UPDATE users SET Money = Money + "+amt+" WHERE User_Name = '"+user+"'";
                    int add_res = c.update(add_qry);
                    if(add_res == 0){
                        c.message("Unable to Add Money to Wallet");
                    }
                    else{
                        int del_res = c.update(del_qry);
                        if(del_res == 0){
                            c.message("Unable to Cancel the Booking.");
                        }
                        else{
                            c.message("Booking Canceled Successfully.");
                            String qry_2 = "INSERT INTO transactions(User_Name,Amount,Info,Date_Time) VALUES ('"+user+"',"+amt+",'Booking Cancelled Money Added',now())";
                            int res_2 = c.update(qry_2);
                            if(res_2 == 1){
                                c.message("Transaction Saved Successfully.");
                            }
                            else{
                                c.message("Unable to Save Transaction.");
                            }
                            load_bookings();
                            id_tf.setText("Booking_ID");
                        }
                    }
                } catch (ClassNotFoundException | SQLException ex) {
                    Logger.getLogger(My_Bookings.class.getName()).log(Level.SEVERE, null, ex);
                }            
            }
            else{}
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        this.setVisible(false);
        try {
            new Home(user).setVisible(true);
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(My_Bookings.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int id = Integer.parseInt(id_tf.getText());
        String qry = "SELECT * FROM tickets WHERE ID = "+id+"";
        try {
            ResultSet rs = c.get_data(qry);
            String b_date = "",t_date = "",t_name = "",source = "",dest = "",dept = "",arrival = "",t_class = "",n1 = "",n2 = "",n3 = "",n4 = "";
            int t_code = 0,otf = 0,a1 = 0,a2 = 0,a3 = 0,a4 = 0;
            double tap = 0;
            if(rs.next()){
                b_date = rs.getString("B_Date");
                t_date = rs.getDate("T_DATE").toString();
                t_code = rs.getInt("Train_Code");
                t_name = rs.getString("Train_Name");
                source = rs.getString("Source");
                dest = rs.getString("Destination");
                dept = rs.getString("Departure");
                arrival = rs.getString("Arrival");
                t_class = rs.getString("Ticket_Class");
                otf = rs.getInt("T_Fare");
                n1 = rs.getString("Name1");
                n2 = rs.getString("Name2");
                n3 = rs.getString("Name3");
                n4 = rs.getString("Name4");
                a1 = rs.getInt("Age1");
                a2 = rs.getInt("Age2");
                a3 = rs.getInt("Age3");
                a4 = rs.getInt("Age4");
                tap = rs.getDouble("Tickets_Total_Amount");
            }
            else{
                c.message("Unable to Fetch Data.");
            }
            ticket_area.setText("");
            ticket_area.append("------------------------------------:> Auros Travels <:------------------------------------\n\n");
            ticket_area.append("     Booking ID :- "+id+"                Booking Date :- "+b_date+"\n     Trip Date :- "+t_date+"\n\n");
            ticket_area.append("------------------------------------:> Train Details <:------------------------------------\n");
            ticket_area.append("    Train Number :- "+t_code+"               ||    Train Name :- "+t_name+"\n");
            ticket_area.append("    Source :- "+source+"                           ||    Destination :- "+dest+"\n");
            ticket_area.append("    Departure :- "+dept+"                        ||    Arrival :- "+arrival+"\n");
            ticket_area.append("    Ticket Class :- "+t_class+"    ||    Per Ticket Amount :- "+otf+"\n\n");
            ticket_area.append("------------------------------------:> Passanger Details <:------------------------------------\n");
            if(n1.length() != 0){
                ticket_area.append("    Name : "+n1+"    ||    Age : "+a1+"\n");
            }
            if(n2.length() != 0){
                ticket_area.append("    Name : "+n2+"    ||    Age : "+a2+"\n");
            }
            if(n3.length() != 0){
                ticket_area.append("    Name : "+n3+"    ||    Age : "+a3+"\n");
            }
            if(n4.length() != 0){
                ticket_area.append("    Name : "+n4+"    ||    Age : "+a4+"\n");
            }
            ticket_area.append("\n");
            ticket_area.append("    Total Amount Paid :- "+tap);
            this.setVisible(false);
            ticket_window.setVisible(true);
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(My_Bookings.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try {
            ticket_area.print();
        } catch (PrinterException ex) {
            Logger.getLogger(My_Bookings.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        ticket_window.setVisible(false);
        new My_Bookings(user).setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(My_Bookings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(My_Bookings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(My_Bookings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(My_Bookings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new My_Bookings().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable booking_table;
    private javax.swing.JTextField id_tf;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel main_panel;
    private javax.swing.JTextArea ticket_area;
    private javax.swing.JFrame ticket_window;
    // End of variables declaration//GEN-END:variables
}
