import java.awt.Color;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Shri
 */
public class Profile extends javax.swing.JFrame {

    Mysql_Con c = new Mysql_Con();
    String user;
    public Profile(String uname) {
        initComponents();
        user = uname;
        load_basic_data();
        load_card_data();
    }

    Profile(JLabel user) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    
    void load_basic_data(){
        try {
            String qry_1 = "SELECT * FROM USERS WHERE User_Name = '"+user+"'";
            ResultSet basic_data = c.get_data(qry_1);
            if(basic_data.next()){
                String fname = basic_data.getString("Full_Name");
                long number = basic_data.getLong("Mobile_Number");
                String mail = basic_data.getString("E_Mail");
                String pass  = basic_data.getString("Password");
                
                full_name.setText(fname);
                mobile_number.setText(number+"");
                email.setText(mail);
                password.setText(pass);
                user_name.setText(user);
            }
            else{
                c.message("Unable to Load Basic Data");
            }
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(Profile.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
    
    void load_card_data(){
        try {
            String qry = "SELECT * FROM card_details WHERE User_Name = '"+user+"'";
            ResultSet card_data = c.get_data(qry);
            if(card_data.next()){
                long cno = card_data.getLong("Account_Number"); 
                int cvv = card_data.getInt("CVV");
                int month = card_data.getInt("Month");
                int year = card_data.getInt("Year");
                
                acnof.setText(""+cno);
                cvvf.setText(""+cvv);
                mf.setText(""+month);
                yf.setText(""+year);
            }
            else{
                c.message("Card Data Not Available.");
                card_details.setVisible(false);
            }
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(Profile.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
    
    private Profile() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        main_screen = new javax.swing.JPanel();
        head = new javax.swing.JLabel();
        basic_details = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        full_name = new javax.swing.JTextField();
        mobile_number = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        password = new javax.swing.JTextField();
        user_name = new javax.swing.JTextField();
        basic_update = new javax.swing.JButton();
        basic_refresh = new javax.swing.JButton();
        basic_clear = new javax.swing.JButton();
        card_details = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        acnof = new javax.swing.JTextField();
        cvvf = new javax.swing.JTextField();
        mf = new javax.swing.JTextField();
        yf = new javax.swing.JTextField();
        basic_update1 = new javax.swing.JButton();
        basic_refresh1 = new javax.swing.JButton();
        basic_clear1 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        main_screen.setBackground(new java.awt.Color(255, 255, 255));
        main_screen.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 0));

        head.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        head.setForeground(new java.awt.Color(0, 0, 255));
        head.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        head.setText("Profile Details");
        head.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 255, 255)));

        basic_details.setBackground(new java.awt.Color(204, 255, 255));
        basic_details.setBorder(javax.swing.BorderFactory.createTitledBorder("Basic Details"));
        basic_details.setForeground(new java.awt.Color(204, 204, 255));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setText("Full Name               :");

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setText("Mobile Number     :");

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setText("E-Mail ID                :");

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setText("User Name            :");

        jLabel6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel6.setText("Password              :");

        full_name.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        mobile_number.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        email.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        password.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        user_name.setEditable(false);
        user_name.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        basic_update.setBackground(new java.awt.Color(255, 255, 255));
        basic_update.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        basic_update.setText("Update");
        basic_update.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                basic_updateMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                basic_updateMouseExited(evt);
            }
        });
        basic_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                basic_updateActionPerformed(evt);
            }
        });

        basic_refresh.setBackground(new java.awt.Color(255, 255, 255));
        basic_refresh.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        basic_refresh.setText("Refresh");
        basic_refresh.setOpaque(false);
        basic_refresh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                basic_refreshMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                basic_refreshMouseExited(evt);
            }
        });
        basic_refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                basic_refreshActionPerformed(evt);
            }
        });

        basic_clear.setBackground(new java.awt.Color(255, 255, 255));
        basic_clear.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        basic_clear.setText("Clear");
        basic_clear.setOpaque(false);
        basic_clear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                basic_clearMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                basic_clearMouseExited(evt);
            }
        });
        basic_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                basic_clearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout basic_detailsLayout = new javax.swing.GroupLayout(basic_details);
        basic_details.setLayout(basic_detailsLayout);
        basic_detailsLayout.setHorizontalGroup(
            basic_detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(basic_detailsLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(basic_detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(basic_detailsLayout.createSequentialGroup()
                        .addGroup(basic_detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(basic_detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(full_name, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mobile_number, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(basic_update))
                    .addGroup(basic_detailsLayout.createSequentialGroup()
                        .addGroup(basic_detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(22, 22, 22)
                        .addGroup(basic_detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(user_name, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addComponent(basic_refresh))
                    .addGroup(basic_detailsLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(23, 23, 23)
                        .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(basic_clear, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        basic_detailsLayout.setVerticalGroup(
            basic_detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(basic_detailsLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(basic_detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(basic_detailsLayout.createSequentialGroup()
                        .addComponent(full_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(mobile_number, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(basic_detailsLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel2)
                        .addGap(17, 17, 17)
                        .addComponent(jLabel3))
                    .addComponent(basic_update, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(basic_detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(basic_detailsLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel4)
                        .addGap(17, 17, 17)
                        .addComponent(jLabel5))
                    .addGroup(basic_detailsLayout.createSequentialGroup()
                        .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(user_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(basic_detailsLayout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(basic_refresh, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(7, 7, 7)
                .addGroup(basic_detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(basic_detailsLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel6))
                    .addGroup(basic_detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(basic_clear)))
                .addGap(6, 6, 6))
        );

        card_details.setBackground(new java.awt.Color(204, 255, 255));
        card_details.setBorder(javax.swing.BorderFactory.createTitledBorder("Card Details"));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setText("Account Number    :");

        jLabel7.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel7.setText("CVV                          :");

        jLabel8.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel8.setText("Month                      :");

        jLabel9.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel9.setText("Year                         :");

        acnof.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        cvvf.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        mf.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        yf.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        basic_update1.setBackground(new java.awt.Color(255, 255, 255));
        basic_update1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        basic_update1.setText("Update");
        basic_update1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                basic_update1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                basic_update1MouseExited(evt);
            }
        });
        basic_update1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                basic_update1ActionPerformed(evt);
            }
        });

        basic_refresh1.setBackground(new java.awt.Color(255, 255, 255));
        basic_refresh1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        basic_refresh1.setText("Refresh");
        basic_refresh1.setOpaque(false);
        basic_refresh1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                basic_refresh1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                basic_refresh1MouseExited(evt);
            }
        });
        basic_refresh1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                basic_refresh1ActionPerformed(evt);
            }
        });

        basic_clear1.setBackground(new java.awt.Color(255, 255, 255));
        basic_clear1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        basic_clear1.setText("Clear");
        basic_clear1.setOpaque(false);
        basic_clear1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                basic_clear1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                basic_clear1MouseExited(evt);
            }
        });
        basic_clear1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                basic_clear1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout card_detailsLayout = new javax.swing.GroupLayout(card_details);
        card_details.setLayout(card_detailsLayout);
        card_detailsLayout.setHorizontalGroup(
            card_detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(card_detailsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(card_detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(card_detailsLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(acnof, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(card_detailsLayout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addComponent(yf))
                    .addGroup(card_detailsLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(cvvf))
                    .addGroup(card_detailsLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(mf)))
                .addGap(18, 18, 18)
                .addGroup(card_detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(basic_refresh1)
                    .addGroup(card_detailsLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(card_detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(basic_update1)
                            .addComponent(basic_clear1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(1, 1, 1))
        );
        card_detailsLayout.setVerticalGroup(
            card_detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(card_detailsLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(card_detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(card_detailsLayout.createSequentialGroup()
                        .addComponent(basic_update1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16)
                        .addComponent(basic_refresh1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(basic_clear1))
                    .addGroup(card_detailsLayout.createSequentialGroup()
                        .addGroup(card_detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(acnof, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(card_detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(cvvf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(card_detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(mf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(card_detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(yf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
        );

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setText("<---Back");
        jButton1.setOpaque(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout main_screenLayout = new javax.swing.GroupLayout(main_screen);
        main_screen.setLayout(main_screenLayout);
        main_screenLayout.setHorizontalGroup(
            main_screenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(head, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(main_screenLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(main_screenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(basic_details, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(card_details, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        main_screenLayout.setVerticalGroup(
            main_screenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(main_screenLayout.createSequentialGroup()
                .addComponent(head)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(basic_details, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(card_details, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(jButton1))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(main_screen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(main_screen, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void basic_clearMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_basic_clearMouseExited
        basic_clear.setBackground(Color.white);
        basic_clear.setForeground(Color.black);
    }//GEN-LAST:event_basic_clearMouseExited

    private void basic_clearMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_basic_clearMouseEntered
        basic_clear.setBackground(Color.red);
        basic_clear.setForeground(Color.white);
    }//GEN-LAST:event_basic_clearMouseEntered

    private void basic_refreshMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_basic_refreshMouseExited
        basic_refresh.setBackground(Color.white);
        basic_refresh.setForeground(Color.black);
    }//GEN-LAST:event_basic_refreshMouseExited

    private void basic_refreshMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_basic_refreshMouseEntered
        basic_refresh.setBackground(Color.green);
        basic_refresh.setForeground(Color.white);
    }//GEN-LAST:event_basic_refreshMouseEntered

    private void basic_update1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_basic_update1MouseEntered
        basic_update1.setBackground(Color.green);
        basic_update1.setForeground(Color.white);
    }//GEN-LAST:event_basic_update1MouseEntered

    private void basic_update1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_basic_update1MouseExited
        basic_update1.setBackground(Color.white);
        basic_update1.setForeground(Color.black);
    }//GEN-LAST:event_basic_update1MouseExited

    private void basic_refresh1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_basic_refresh1MouseEntered
        basic_refresh1.setBackground(Color.green);
        basic_refresh1.setForeground(Color.white);
    }//GEN-LAST:event_basic_refresh1MouseEntered

    private void basic_refresh1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_basic_refresh1MouseExited
        basic_refresh1.setBackground(Color.white);
        basic_refresh1.setForeground(Color.black);
    }//GEN-LAST:event_basic_refresh1MouseExited

    private void basic_clear1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_basic_clear1MouseEntered
        basic_clear1.setBackground(Color.red);
        basic_clear1.setForeground(Color.white);
    }//GEN-LAST:event_basic_clear1MouseEntered

    private void basic_clear1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_basic_clear1MouseExited
        basic_clear1.setBackground(Color.white);
        basic_clear1.setForeground(Color.black);
    }//GEN-LAST:event_basic_clear1MouseExited

    private void basic_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_basic_updateActionPerformed
        String new_name = full_name.getText();
        double new_number = Double.parseDouble(mobile_number.getText());
        String new_mail = email.getText();
        String new_pass = password.getText();
        
        if(new_name.length() == 0 || new_mail.length() == 0 || new_pass.length() == 0 || new_number == 0){
            c.message("Please Fill All Fields.");
        }
        else{
            String qry = "UPDATE USERS SET Full_Name = '"+new_name+"' , Mobile_Number = "+new_number+" , E_Mail = '"+new_mail+"' , Password = '"+new_pass+"'";
            try {
                int res = c.update(qry);
                if(res == 0){
                    c.message("Unable To Update Details.");
                }
                else{
                    c.message("Details Update Successfully.");
                    full_name.setText("");
                    mobile_number.setText("");
                    email.setText("");
                    user_name.setText("");
                    password.setText("");
                }
            } catch (ClassNotFoundException | SQLException ex) {
                Logger.getLogger(Profile.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
    }//GEN-LAST:event_basic_updateActionPerformed

    private void basic_updateMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_basic_updateMouseExited
        basic_update.setBackground(Color.white);
        basic_update.setForeground(Color.black);
    }//GEN-LAST:event_basic_updateMouseExited

    private void basic_updateMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_basic_updateMouseEntered
        basic_update.setBackground(Color.blue);
        basic_update.setForeground(Color.white);
    }//GEN-LAST:event_basic_updateMouseEntered

    private void basic_refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_basic_refreshActionPerformed
        load_basic_data();
    }//GEN-LAST:event_basic_refreshActionPerformed

    private void basic_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_basic_clearActionPerformed
        full_name.setText("");
        mobile_number.setText("");
        email.setText("");
        user_name.setText("");
        password.setText("");
    }//GEN-LAST:event_basic_clearActionPerformed

    private void basic_refresh1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_basic_refresh1ActionPerformed
        load_card_data();
    }//GEN-LAST:event_basic_refresh1ActionPerformed

    private void basic_clear1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_basic_clear1ActionPerformed
        acnof.setText("");
        cvvf.setText("");
        mf.setText("");
        yf.setText("");
    }//GEN-LAST:event_basic_clear1ActionPerformed

    private void basic_update1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_basic_update1ActionPerformed
        String new_acno = acnof.getText();
        int new_cvv = Integer.parseInt(cvvf.getText());
        int new_m = Integer.parseInt(mf.getText());
        int new_y = Integer.parseInt(yf.getText());
        
        if(new_acno.length() == 0 || new_cvv == 0 || new_m == 0 || new_y == 0){
            c.message("Please Fill All the Fields then Update Data.");
        }
        else{
            String qry = "UPDATE card_details SET ACcount_Number = '"+new_acno+"' , CVV = "+new_cvv+" , Month = "+new_m+" , Year = "+new_y+"";
            try {
                int res = c.update(qry);
                if(res == 0){
                    c.message("Unable to Update Information.");
                }
                else{
                    c.message("Data Updated Successfully.");
                    acnof.setText("");
                    cvvf.setText("");
                    mf.setText("");
                    yf.setText("");
                }
            } catch (ClassNotFoundException | SQLException ex) {
                Logger.getLogger(Profile.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_basic_update1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            this.setVisible(false);
            new Home(user).setVisible(true);
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(Profile.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Profile().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField acnof;
    private javax.swing.JButton basic_clear;
    private javax.swing.JButton basic_clear1;
    private javax.swing.JPanel basic_details;
    private javax.swing.JButton basic_refresh;
    private javax.swing.JButton basic_refresh1;
    private javax.swing.JButton basic_update;
    private javax.swing.JButton basic_update1;
    private javax.swing.JPanel card_details;
    private javax.swing.JTextField cvvf;
    private javax.swing.JTextField email;
    private javax.swing.JTextField full_name;
    private javax.swing.JLabel head;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel main_screen;
    private javax.swing.JTextField mf;
    private javax.swing.JTextField mobile_number;
    private javax.swing.JTextField password;
    private javax.swing.JTextField user_name;
    private javax.swing.JTextField yf;
    // End of variables declaration//GEN-END:variables
}
