
import java.awt.Color;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Shri
 */
public class Transfer_Money extends javax.swing.JFrame {

    Mysql_Con c = new Mysql_Con();
    String user = "";
    public Transfer_Money(String uname) {
        initComponents();
        user = uname;
        fun();
    }
    
    
    void fun(){
        String qry = "SELECT Money FROM users WHERE User_Name = '"+user+"'";
        double amount = 0;
        try {
            ResultSet amt = c.get_data(qry);
            if(amt.next()){
                amount = amt.getDouble("Money");
                ab_tf.setText(""+amount);
            }
            else{
                c.message("Unable to Get Amount from Database");
            }
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(Transfer_Money.class.getName()).log(Level.SEVERE, null, ex);
        }
        check_btn.setBackground(Color.white);
        check_btn.setForeground(Color.black);
        uname_tf.setText("User_Name");
        transfer_amt_tf.setText("");
        transfer_amt_tf.setEditable(false);
        trans_amt_btn.setEnabled(false);
    }
    
    
    private Transfer_Money() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        ab_tf = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        uname_tf = new javax.swing.JTextField();
        check_btn = new javax.swing.JButton();
        trans_amt_btn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        transfer_amt_tf = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 153), 10));

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel1.setText("Available Balance");

        ab_tf.setEditable(false);
        ab_tf.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel2.setText("Transfer To");

        uname_tf.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        uname_tf.setText("User_Name");

        check_btn.setBackground(new java.awt.Color(255, 255, 255));
        check_btn.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        check_btn.setText("Check");
        check_btn.setOpaque(false);
        check_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                check_btnActionPerformed(evt);
            }
        });

        trans_amt_btn.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        trans_amt_btn.setText("Transfer Amount");
        trans_amt_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trans_amt_btnActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel3.setText("Transfer Amount");

        transfer_amt_tf.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N

        jLabel4.setFont(new java.awt.Font("SansSerif", 1, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 102, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Transfer Amount");
        jLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 255), 2));
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(trans_amt_btn))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ab_tf)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(uname_tf, javax.swing.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(check_btn))
                            .addComponent(transfer_amt_tf))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(ab_tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(uname_tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(check_btn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(transfer_amt_tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(trans_amt_btn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        this.setVisible(false);
        try {
            new Home(user).setVisible(true);
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(Transfer_Money.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jLabel4MouseClicked

    private void check_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_check_btnActionPerformed
        String foreign_user = uname_tf.getText();
        String qry = "SELECT User_Name FROM users WHERE User_Name = '"+foreign_user+"'";
        try {
            int num_users = c.row_count(qry);
            if(num_users == 1){
                check_btn.setText("Available");
                check_btn.setBackground(Color.green);
                check_btn.setForeground(Color.black);
                transfer_amt_tf.setEditable(true);
                trans_amt_btn.setEnabled(true);
                uname_tf.setEditable(false);
            }
            else{
                check_btn.setText("Not Available");
                check_btn.setBackground(Color.red);
                check_btn.setForeground(Color.black);
                transfer_amt_tf.setEditable(false);
                trans_amt_btn.setEnabled(false);
            }
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(Transfer_Money.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_check_btnActionPerformed

    private void trans_amt_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trans_amt_btnActionPerformed
        double aamt = Double.parseDouble(ab_tf.getText());
        double tamt = Double.parseDouble(transfer_amt_tf.getText());
        String foreign_user = uname_tf.getText();
        if(Double.toString(tamt).length() == 0){
            c.message("Please fill Transfer Amount Field");
        }
        else{
            if(aamt < tamt){
                c.message("Transfer Amount Should be Equal or Greater than Available Amount");
            }
            else{
                String less_qry = "UPDATE users SET Money = Money -"+tamt+" WHERE User_Name = '"+user+"'";
                String add_qry = "UPDATE users SET Money = Money +"+tamt+" WHERE User_Name = '"+foreign_user+"'";
                try {
                    int less_res = c.update(less_qry);
                    if(less_res == 0){
                        c.message("Unable to Deduct Money from Your Account");
                    }
                    else{
                        int add_res = c.update(add_qry);
                        if(add_res == 0){
                            c.message("Money Deducted but not able to Transfer Monet to "+foreign_user);
                        }
                        else{
                            c.message("Money Transfered Successfully");
                            String qry_1 = "INSERT INTO transactions(User_Name,Amount,Info,Date_Time) VALUES ('"+user+"',"+tamt+",'Money Transfered to "+foreign_user+"',now())";
                            String qry_2 = "INSERT INTO transactions(User_Name,Amount,Info,Date_Time) VALUES ('"+foreign_user+"',"+tamt+",'Money Recived from "+user+"',now())";
                            int res_1 = c.update(qry_1);
                            int res_2 = c.update(qry_2);
                            if(res_1 == 1 && res_2 == 1){}
                            else{
                                c.message("Unable to Save Transaction.");
                            }
                            fun();
                        }
                    }
                } catch (ClassNotFoundException | SQLException ex) {
                    Logger.getLogger(Transfer_Money.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    }//GEN-LAST:event_trans_amt_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Transfer_Money.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Transfer_Money.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Transfer_Money.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Transfer_Money.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Transfer_Money().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ab_tf;
    private javax.swing.JButton check_btn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton trans_amt_btn;
    private javax.swing.JTextField transfer_amt_tf;
    private javax.swing.JTextField uname_tf;
    // End of variables declaration//GEN-END:variables
}
