import java.awt.Color;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.*;

public class User_Transactions extends javax.swing.JFrame {

    /**
     * Creates new form User_Transactions
     * @param uname
     */
    Mysql_Con c = new Mysql_Con(); 
    String uname;
    public User_Transactions(String user) {
        initComponents();
        uname = user;
        load_transactions(uname);
    }
        
    void load_transactions(String uname){
        if(uname.equals("admin")){
            String qry = " SELECT Info,Amount,DATE_TIME,User_Name FROM TRANSACTIONS ";
            DefaultTableModel model = (DefaultTableModel) data_table.getModel();
            try {
                ResultSet data = c.get_data(qry);
                while(data.next()){
                    String user = data.getString("User_Name");
                    String info = data.getString("Info");
                    double amt = data.getDouble("Amount");
                    String date_time = data.getString("DATE_TIME");
                    Object[] rowData = {user+" : "+info,amt,date_time};
                    model.addRow(rowData);
                }
            } catch (ClassNotFoundException | SQLException ex) {
                Logger.getLogger(User_Transactions.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else{
            String qry = "SELECT Info,Amount,DATE_TIME FROM TRANSACTIONS WHERE User_Name = '"+uname+"'";
            DefaultTableModel model = (DefaultTableModel) data_table.getModel();
            try {
                ResultSet data = c.get_data(qry);
                while(data.next()){
                    String info = data.getString("Info");
                    double amt = data.getDouble("Amount");
                    String date_time = data.getString("DATE_TIME");
                    Object[] rowData = {info,amt,date_time};
                    model.addRow(rowData);
                }
            } catch (ClassNotFoundException | SQLException ex) {
                Logger.getLogger(User_Transactions.class.getName()).log(Level.SEVERE, null, ex);
            }
        }   
    }

    private User_Transactions() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        screen = new javax.swing.JPanel();
        head_screen = new javax.swing.JPanel();
        head = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        data_table = new javax.swing.JTable();
        back_btn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFocusable(false);
        setUndecorated(true);
        setResizable(false);

        screen.setBackground(new java.awt.Color(255, 255, 255));

        head_screen.setBackground(new java.awt.Color(153, 153, 255));

        head.setFont(new java.awt.Font("Traditional Arabic", 1, 36)); // NOI18N
        head.setForeground(new java.awt.Color(255, 255, 0));
        head.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        head.setText("Transactions");

        javax.swing.GroupLayout head_screenLayout = new javax.swing.GroupLayout(head_screen);
        head_screen.setLayout(head_screenLayout);
        head_screenLayout.setHorizontalGroup(
            head_screenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(head_screenLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(head, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        head_screenLayout.setVerticalGroup(
            head_screenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(head_screenLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(head, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        data_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Description", "Amount", "Date and Time"
            }
        ));
        data_table.setEnabled(false);
        jScrollPane1.setViewportView(data_table);

        back_btn.setBackground(new java.awt.Color(255, 255, 255));
        back_btn.setFont(new java.awt.Font("Microsoft Yi Baiti", 1, 24)); // NOI18N
        back_btn.setText("<---Back");
        back_btn.setOpaque(false);
        back_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                back_btnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                back_btnMouseExited(evt);
            }
        });
        back_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout screenLayout = new javax.swing.GroupLayout(screen);
        screen.setLayout(screenLayout);
        screenLayout.setHorizontalGroup(
            screenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(head_screen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(screenLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(screenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 610, Short.MAX_VALUE)
                    .addComponent(back_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        screenLayout.setVerticalGroup(
            screenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(screenLayout.createSequentialGroup()
                .addComponent(head_screen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(back_btn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(screen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(screen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void back_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_btnActionPerformed
        if(uname.equals("admin")){
            this.setVisible(false);
            new Admin_Panel().setVisible(true);
        }
        else{
            try {
            new Home(uname).setVisible(true);
            this.setVisible(false);
            } catch (ClassNotFoundException | SQLException ex) {
                Logger.getLogger(User_Transactions.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_back_btnActionPerformed

    private void back_btnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_back_btnMouseEntered
        back_btn.setBackground(Color.blue);
        back_btn.setForeground(Color.white);
    }//GEN-LAST:event_back_btnMouseEntered

    private void back_btnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_back_btnMouseExited
        back_btn.setBackground(Color.white);
        back_btn.setForeground(Color.black);
    }//GEN-LAST:event_back_btnMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(User_Transactions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(User_Transactions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(User_Transactions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(User_Transactions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new User_Transactions().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back_btn;
    private javax.swing.JTable data_table;
    private javax.swing.JLabel head;
    private javax.swing.JPanel head_screen;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel screen;
    // End of variables declaration//GEN-END:variables
}
